### PR TITLE
Set unique android.namespaces for all the extensions

### LINKED ISSUE #45: Duplicate class error when using multiple android extensions
I get the following build error when I'm using multiple of the Android extension libraries:

> Duplicate class com.github.ajalt.colormath.BuildConfig found in modules colormath-ext-android-colorint-release-runtime (com.github.ajalt.colormath:colormath-ext-android-colorint-android:3.3.2) and colormath-ext-jetpack-compose-release-runtime (com.github.ajalt.colormath:colormath-ext-jetpack-compose-android:3.3.2)

This is due to using the same `android.namespace` value in the gradle build script for those extensions

### PR DESCRIPTION
**Pull request by frett**
these values are what were originally set in the `AndroidManifest.xml`. It doesn't matter too much what they are set to, just as long as they are unique and don't collide with other namespaces

Fixes #45

### CODE REVIEW

**Comment by ajalt** [comment]
Excellent, thank you!

Do you know what the backwards compatibility is for changing these?

**Comment by frett** [comment]
It would change the location of the `BuildConfig` class generated for each extension (which actually would revert to the location that was in 3.2.1).But I'm not aware of any use of the generated BuildConfig for those extensions

**Comment by JakeWharton** [comment]
You should consider disabling the `BuildConfig` generation. It's off-by-default in AGP 8 for libraries anyway.

**Comment by frett** [comment]
@ajalt I can add that to this PR if you want

**Comment by ajalt** [comment]
yes please, if it's not necessary, let's get rid of it

**Comment by frett** [comment]
I think the namespace change should stay to prevent any future conflicts. I know the `R` class is also generated under that namespace, but you aren't including any android resources that would be affected by that

**Pull request merged**
